In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [11]:
np.random.rand(5)

array([0.23911463, 0.53956769, 0.63265115, 0.41976163, 0.30918467])

In [12]:
np.random.randn(4,4) #standard distribution

array([[ 1.05029245, -0.29657039, -0.0805213 ,  0.91120929],
       [ 0.05994965, -0.42611417,  0.63619808,  1.14036417],
       [-0.7068712 ,  1.09352113, -0.24541692, -1.63222097],
       [ 0.39976919,  0.04035643, -0.77734584, -0.97182547]])

In [14]:
np.random.randint(1,100,5)

array([21, 95, 40, 73, 69])

In [22]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr = np.random.randint(10, 12, 10)
ranarr

array([10, 11, 10, 11, 11, 10, 11, 11, 11, 10])

In [28]:
arr.reshape(5,5) #rows x columns must equal number of elements in the array being reshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
ranarr.max()

11

In [32]:
ranarr.min()

10

In [38]:
ranarr.argmax()

1

In [41]:
arr.reshape(5,5).shape

(5, 5)

In [43]:
arr.dtype

dtype('int32')

In [45]:
from numpy.random import randint

In [46]:
randint(2,10)

4