In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

8

In [8]:
arr[1:5]

array([1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
arr = np.arange(0,11)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_arr = arr[0:6]

In [19]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [21]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [23]:
slice_of_arr[:] = 99

In [24]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_copy = arr.copy()

In [28]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
arr_copy[:] = 100

In [30]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [31]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [33]:
arr_2d = np.array([[5,10,15], [20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
arr_2d[0][0]

5

In [38]:
arr_2d[2,1] #recommended method [row, column]

40

In [39]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [40]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [42]:
arr = np.arange(1,11)

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
bool_arr = arr > 5 #makes a new array which returns boolean array

In [47]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [48]:
arr[bool_arr] #returns instances where bool_arr is true

array([ 6,  7,  8,  9, 10])

In [50]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [57]:
arr[arr%2]

array([2, 1, 2, 1, 2, 1, 2, 1, 2, 1])

In [58]:
arr_2d = np.arange(50).reshape(5,10)

In [60]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])